// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { CoursesCreateData, CoursesCreateErrors, CoursesCreateResponses, CoursesDestroyData, CoursesDestroyErrors, CoursesDestroyResponses, CoursesIndexData, CoursesIndexErrors, CoursesIndexResponses, CoursesLessonsCreateData, CoursesLessonsCreateErrors, CoursesLessonsCreateResponses, CoursesLessonsDestroyData, CoursesLessonsDestroyErrors, CoursesLessonsDestroyResponses, CoursesLessonsIndexData, CoursesLessonsIndexErrors, CoursesLessonsIndexResponses, CoursesLessonsShowData, CoursesLessonsShowErrors, CoursesLessonsShowResponses, CoursesLessonsUpdateData, CoursesLessonsUpdateErrors, CoursesLessonsUpdateResponses, CoursesShowData, CoursesShowErrors, CoursesShowResponses, CoursesUpdateData, CoursesUpdateErrors, CoursesUpdateResponses, TokensCreateData, TokensCreateErrors, TokensCreateResponses, UsersCreateData, UsersCreateErrors, UsersCreateResponses, UsersDestroyData, UsersDestroyErrors, UsersDestroyResponses, UsersIndexData, UsersIndexErrors, UsersIndexResponses, UsersShowData, UsersShowErrors, UsersShowResponses, UsersUpdateData, UsersUpdateErrors, UsersUpdateResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Список курсов
 */
export const coursesIndex = <ThrowOnError extends boolean = false>(options?: Options<CoursesIndexData, ThrowOnError>): RequestResult<CoursesIndexResponses, CoursesIndexErrors, ThrowOnError> => (options?.client ?? client).get<CoursesIndexResponses, CoursesIndexErrors, ThrowOnError>({ url: '/courses', ...options });

/**
 * Создание курса
 */
export const coursesCreate = <ThrowOnError extends boolean = false>(options: Options<CoursesCreateData, ThrowOnError>): RequestResult<CoursesCreateResponses, CoursesCreateErrors, ThrowOnError> => (options.client ?? client).post<CoursesCreateResponses, CoursesCreateErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/courses',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Список уроков курса
 */
export const coursesLessonsIndex = <ThrowOnError extends boolean = false>(options: Options<CoursesLessonsIndexData, ThrowOnError>): RequestResult<CoursesLessonsIndexResponses, CoursesLessonsIndexErrors, ThrowOnError> => (options.client ?? client).get<CoursesLessonsIndexResponses, CoursesLessonsIndexErrors, ThrowOnError>({ url: '/courses/{courseId}/lessons', ...options });

/**
 * Добавление урока в курс
 */
export const coursesLessonsCreate = <ThrowOnError extends boolean = false>(options: Options<CoursesLessonsCreateData, ThrowOnError>): RequestResult<CoursesLessonsCreateResponses, CoursesLessonsCreateErrors, ThrowOnError> => (options.client ?? client).post<CoursesLessonsCreateResponses, CoursesLessonsCreateErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/courses/{courseId}/lessons',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Удаление урока
 */
export const coursesLessonsDestroy = <ThrowOnError extends boolean = false>(options: Options<CoursesLessonsDestroyData, ThrowOnError>): RequestResult<CoursesLessonsDestroyResponses, CoursesLessonsDestroyErrors, ThrowOnError> => (options.client ?? client).delete<CoursesLessonsDestroyResponses, CoursesLessonsDestroyErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/courses/{courseId}/lessons/{id}',
  ...options
});

/**
 * Урок курса
 */
export const coursesLessonsShow = <ThrowOnError extends boolean = false>(options: Options<CoursesLessonsShowData, ThrowOnError>): RequestResult<CoursesLessonsShowResponses, CoursesLessonsShowErrors, ThrowOnError> => (options.client ?? client).get<CoursesLessonsShowResponses, CoursesLessonsShowErrors, ThrowOnError>({ url: '/courses/{courseId}/lessons/{id}', ...options });

/**
 * Изменение урока
 */
export const coursesLessonsUpdate = <ThrowOnError extends boolean = false>(options: Options<CoursesLessonsUpdateData, ThrowOnError>): RequestResult<CoursesLessonsUpdateResponses, CoursesLessonsUpdateErrors, ThrowOnError> => (options.client ?? client).put<CoursesLessonsUpdateResponses, CoursesLessonsUpdateErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/courses/{courseId}/lessons/{id}',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Удаление курса
 */
export const coursesDestroy = <ThrowOnError extends boolean = false>(options: Options<CoursesDestroyData, ThrowOnError>): RequestResult<CoursesDestroyResponses, CoursesDestroyErrors, ThrowOnError> => (options.client ?? client).delete<CoursesDestroyResponses, CoursesDestroyErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/courses/{id}',
  ...options
});

/**
 * Курс по идентификатору
 */
export const coursesShow = <ThrowOnError extends boolean = false>(options: Options<CoursesShowData, ThrowOnError>): RequestResult<CoursesShowResponses, CoursesShowErrors, ThrowOnError> => (options.client ?? client).get<CoursesShowResponses, CoursesShowErrors, ThrowOnError>({ url: '/courses/{id}', ...options });

/**
 * Изменение курса
 */
export const coursesUpdate = <ThrowOnError extends boolean = false>(options: Options<CoursesUpdateData, ThrowOnError>): RequestResult<CoursesUpdateResponses, CoursesUpdateErrors, ThrowOnError> => (options.client ?? client).put<CoursesUpdateResponses, CoursesUpdateErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/courses/{id}',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Выдача токена по email и паролю
 */
export const tokensCreate = <ThrowOnError extends boolean = false>(options: Options<TokensCreateData, ThrowOnError>): RequestResult<TokensCreateResponses, TokensCreateErrors, ThrowOnError> => (options.client ?? client).post<TokensCreateResponses, TokensCreateErrors, ThrowOnError>({
  url: '/tokens',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Список пользователей
 */
export const usersIndex = <ThrowOnError extends boolean = false>(options?: Options<UsersIndexData, ThrowOnError>): RequestResult<UsersIndexResponses, UsersIndexErrors, ThrowOnError> => (options?.client ?? client).get<UsersIndexResponses, UsersIndexErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/users',
  ...options
});

/**
 * Регистрация пользователя
 */
export const usersCreate = <ThrowOnError extends boolean = false>(options: Options<UsersCreateData, ThrowOnError>): RequestResult<UsersCreateResponses, UsersCreateErrors, ThrowOnError> => (options.client ?? client).post<UsersCreateResponses, UsersCreateErrors, ThrowOnError>({
  url: '/users',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Удаление пользователя
 */
export const usersDestroy = <ThrowOnError extends boolean = false>(options: Options<UsersDestroyData, ThrowOnError>): RequestResult<UsersDestroyResponses, UsersDestroyErrors, ThrowOnError> => (options.client ?? client).delete<UsersDestroyResponses, UsersDestroyErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/users/{id}',
  ...options
});

/**
 * Пользователь по идентификатору
 */
export const usersShow = <ThrowOnError extends boolean = false>(options: Options<UsersShowData, ThrowOnError>): RequestResult<UsersShowResponses, UsersShowErrors, ThrowOnError> => (options.client ?? client).get<UsersShowResponses, UsersShowErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/users/{id}',
  ...options
});

/**
 * Изменение пользователя
 */
export const usersUpdate = <ThrowOnError extends boolean = false>(options: Options<UsersUpdateData, ThrowOnError>): RequestResult<UsersUpdateResponses, UsersUpdateErrors, ThrowOnError> => (options.client ?? client).put<UsersUpdateResponses, UsersUpdateErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/users/{id}',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});
