// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:3000' | (string & {});
};

export type AuthInfo = {
  email: string;
  password: string;
};

export type BadRequestError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

export type ConflictError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

export type Course = {
  id: number;
  name: string;
  description: string;
};

export type CourseCreateDto = {
  name: string;
  description: string;
};

export type CourseEditDto = {
  name?: string;
  description?: string;
};

export type CourseLesson = {
  id: number;
  courseId: number;
  name: string;
  body: string;
};

export type CourseLessonCreateDto = {
  name: string;
  body: string;
};

export type CourseLessonEditDto = {
  name?: string;
  body?: string;
};

export type ForbiddenError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

export type NotFoundError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

export type PageMeta = {
  page: number;
  perPage: number;
  total: number;
  totalPages: number;
};

export type PreconditionFailedError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

/**
 * https://www.rfc-editor.org/rfc/rfc9457.html
 */
export type ProblemDetails = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

export type Timestamps = {
  [key: string]: unknown;
};

export type TokenInfo = {
  token: string;
};

export type TooManyRequestsError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

export type UnauthorizedError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

export type UnprocessableEntityError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  errors: Array<{
    message: string;
    rule: string;
    field: string;
  }>;
};

export type User = {
  id: number;
  fullName: string | null;
  email: string;
};

export type UserCreateDto = {
  fullName?: string;
  email: string;
  password: string;
};

export type UserEditDto = {
  fullName?: string;
  password?: string;
};

export type Versions = 'v1' | 'v2';

export type CoursesIndexData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    perPage?: number;
  };
  url: '/courses';
};

export type CoursesIndexErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type CoursesIndexError = CoursesIndexErrors[keyof CoursesIndexErrors];

export type CoursesIndexResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    data: Array<Course>;
    meta: PageMeta;
  };
};

export type CoursesIndexResponse = CoursesIndexResponses[keyof CoursesIndexResponses];

export type CoursesCreateData = {
  body: CourseCreateDto;
  path?: never;
  query?: never;
  url: '/courses';
};

export type CoursesCreateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * Client error
   */
  422: UnprocessableEntityError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type CoursesCreateError = CoursesCreateErrors[keyof CoursesCreateErrors];

export type CoursesCreateResponses = {
  /**
   * The request has succeeded and a new resource has been created as a result.
   */
  201: Course;
};

export type CoursesCreateResponse = CoursesCreateResponses[keyof CoursesCreateResponses];

export type CoursesLessonsIndexData = {
  body?: never;
  path: {
    courseId: number;
  };
  query?: {
    page?: number;
    perPage?: number;
  };
  url: '/courses/{courseId}/lessons';
};

export type CoursesLessonsIndexErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type CoursesLessonsIndexError = CoursesLessonsIndexErrors[keyof CoursesLessonsIndexErrors];

export type CoursesLessonsIndexResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    data: Array<CourseLesson>;
    meta: PageMeta;
  };
};

export type CoursesLessonsIndexResponse = CoursesLessonsIndexResponses[keyof CoursesLessonsIndexResponses];

export type CoursesLessonsCreateData = {
  body: CourseLessonCreateDto;
  path: {
    courseId: number;
  };
  query?: never;
  url: '/courses/{courseId}/lessons';
};

export type CoursesLessonsCreateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * Access is forbidden.
   */
  403: ForbiddenError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Client error
   */
  422: UnprocessableEntityError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type CoursesLessonsCreateError = CoursesLessonsCreateErrors[keyof CoursesLessonsCreateErrors];

export type CoursesLessonsCreateResponses = {
  /**
   * The request has succeeded and a new resource has been created as a result.
   */
  201: CourseLesson;
};

export type CoursesLessonsCreateResponse = CoursesLessonsCreateResponses[keyof CoursesLessonsCreateResponses];

export type CoursesLessonsDestroyData = {
  body?: never;
  path: {
    courseId: number;
    id: number;
  };
  query?: never;
  url: '/courses/{courseId}/lessons/{id}';
};

export type CoursesLessonsDestroyErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * Access is forbidden.
   */
  403: ForbiddenError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type CoursesLessonsDestroyError = CoursesLessonsDestroyErrors[keyof CoursesLessonsDestroyErrors];

export type CoursesLessonsDestroyResponses = {
  /**
   * There is no content to send for this request, but the headers may be useful.
   */
  204: void;
};

export type CoursesLessonsDestroyResponse = CoursesLessonsDestroyResponses[keyof CoursesLessonsDestroyResponses];

export type CoursesLessonsShowData = {
  body?: never;
  path: {
    courseId: number;
    id: number;
  };
  query?: never;
  url: '/courses/{courseId}/lessons/{id}';
};

export type CoursesLessonsShowErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type CoursesLessonsShowError = CoursesLessonsShowErrors[keyof CoursesLessonsShowErrors];

export type CoursesLessonsShowResponses = {
  /**
   * The request has succeeded.
   */
  200: CourseLesson;
};

export type CoursesLessonsShowResponse = CoursesLessonsShowResponses[keyof CoursesLessonsShowResponses];

export type CoursesLessonsUpdateData = {
  body: CourseLessonEditDto;
  path: {
    courseId: number;
    id: number;
  };
  query?: never;
  url: '/courses/{courseId}/lessons/{id}';
};

export type CoursesLessonsUpdateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * Access is forbidden.
   */
  403: ForbiddenError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Precondition failed.
   */
  412: PreconditionFailedError;
  /**
   * Client error
   */
  422: UnprocessableEntityError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type CoursesLessonsUpdateError = CoursesLessonsUpdateErrors[keyof CoursesLessonsUpdateErrors];

export type CoursesLessonsUpdateResponses = {
  /**
   * The request has succeeded.
   */
  200: CourseLesson;
};

export type CoursesLessonsUpdateResponse = CoursesLessonsUpdateResponses[keyof CoursesLessonsUpdateResponses];

export type CoursesDestroyData = {
  body?: never;
  headers?: {
    /**
     * ETag из предыдущего GET; см. update.
     */
    'If-Match'?: string;
  };
  path: {
    id: number;
  };
  query?: never;
  url: '/courses/{id}';
};

export type CoursesDestroyErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * Access is forbidden.
   */
  403: ForbiddenError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Precondition failed.
   */
  412: PreconditionFailedError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type CoursesDestroyError = CoursesDestroyErrors[keyof CoursesDestroyErrors];

export type CoursesDestroyResponses = {
  /**
   * There is no content to send for this request, but the headers may be useful.
   */
  204: void;
};

export type CoursesDestroyResponse = CoursesDestroyResponses[keyof CoursesDestroyResponses];

export type CoursesShowData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/courses/{id}';
};

export type CoursesShowErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type CoursesShowError = CoursesShowErrors[keyof CoursesShowErrors];

export type CoursesShowResponses = {
  /**
   * The request has succeeded.
   */
  200: Course;
};

export type CoursesShowResponse = CoursesShowResponses[keyof CoursesShowResponses];

export type CoursesUpdateData = {
  body: CourseEditDto;
  headers?: {
    /**
     * ETag из предыдущего GET. Необязателен; если прислан и запись с тех пор
     * изменилась, правка отклоняется с 412.
     */
    'If-Match'?: string;
  };
  path: {
    id: number;
  };
  query?: never;
  url: '/courses/{id}';
};

export type CoursesUpdateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * Access is forbidden.
   */
  403: ForbiddenError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Precondition failed.
   */
  412: PreconditionFailedError;
  /**
   * Client error
   */
  422: UnprocessableEntityError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type CoursesUpdateError = CoursesUpdateErrors[keyof CoursesUpdateErrors];

export type CoursesUpdateResponses = {
  /**
   * The request has succeeded.
   */
  200: Course;
};

export type CoursesUpdateResponse = CoursesUpdateResponses[keyof CoursesUpdateResponses];

export type TokensCreateData = {
  body: AuthInfo;
  path?: never;
  query?: never;
  url: '/tokens';
};

export type TokensCreateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * Client error
   */
  422: UnprocessableEntityError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type TokensCreateError = TokensCreateErrors[keyof TokensCreateErrors];

export type TokensCreateResponses = {
  /**
   * The request has succeeded and a new resource has been created as a result.
   */
  201: TokenInfo;
};

export type TokensCreateResponse = TokensCreateResponses[keyof TokensCreateResponses];

export type UsersIndexData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    perPage?: number;
  };
  url: '/users';
};

export type UsersIndexErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type UsersIndexError = UsersIndexErrors[keyof UsersIndexErrors];

export type UsersIndexResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    data: Array<User>;
    meta: PageMeta;
  };
};

export type UsersIndexResponse = UsersIndexResponses[keyof UsersIndexResponses];

export type UsersCreateData = {
  body: UserCreateDto;
  path?: never;
  query?: never;
  url: '/users';
};

export type UsersCreateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Client error
   */
  422: UnprocessableEntityError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type UsersCreateError = UsersCreateErrors[keyof UsersCreateErrors];

export type UsersCreateResponses = {
  /**
   * The request has succeeded and a new resource has been created as a result.
   */
  201: User;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/users/{id}';
};

export type UsersDestroyErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * The request conflicts with the current state of the server.
   */
  409: ConflictError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type UsersDestroyError = UsersDestroyErrors[keyof UsersDestroyErrors];

export type UsersDestroyResponses = {
  /**
   * There is no content to send for this request, but the headers may be useful.
   */
  204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersShowData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/users/{id}';
};

export type UsersShowErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type UsersShowError = UsersShowErrors[keyof UsersShowErrors];

export type UsersShowResponses = {
  /**
   * The request has succeeded.
   */
  200: User;
};

export type UsersShowResponse = UsersShowResponses[keyof UsersShowResponses];

export type UsersUpdateData = {
  body: UserEditDto;
  path: {
    id: number;
  };
  query?: never;
  url: '/users/{id}';
};

export type UsersUpdateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: BadRequestError;
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Client error
   */
  422: UnprocessableEntityError;
  /**
   * Client error
   */
  429: TooManyRequestsError;
};

export type UsersUpdateError = UsersUpdateErrors[keyof UsersUpdateErrors];

export type UsersUpdateResponses = {
  /**
   * The request has succeeded.
   */
  200: User;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];
