// This file is auto-generated by @hey-api/openapi-ts

import type {
  CoursesIndexData,
  CoursesIndexResponses,
  CoursesCreateData,
  CoursesCreateErrors,
  CoursesCreateResponses,
  CoursesLessonsIndexData,
  CoursesLessonsIndexResponses,
  CoursesLessonsCreateData,
  CoursesLessonsCreateErrors,
  CoursesLessonsCreateResponses,
  CoursesLessonsShowData,
  CoursesLessonsShowErrors,
  CoursesLessonsShowResponses,
  CoursesDestroyData,
  CoursesDestroyErrors,
  CoursesDestroyResponses,
  CoursesShowData,
  CoursesShowErrors,
  CoursesShowResponses,
  CoursesUpdateData,
  CoursesUpdateErrors,
  CoursesUpdateResponses,
  TokensCreateData,
  TokensCreateErrors,
  TokensCreateResponses,
  UsersIndexData,
  UsersIndexResponses,
  UsersCreateData,
  UsersCreateErrors,
  UsersCreateResponses,
  UsersDestroyData,
  UsersDestroyErrors,
  UsersDestroyResponses,
  UsersShowData,
  UsersShowErrors,
  UsersShowResponses,
  UsersUpdateData,
  UsersUpdateErrors,
  UsersUpdateResponses,
} from "./types.gen.js";
import type { RouteHandler } from "fastify";

export type RouteHandlers = {
  coursesIndex: RouteHandler<{
    Querystring?: CoursesIndexData["query"];
    Reply: CoursesIndexResponses;
  }>;
  coursesCreate: RouteHandler<{
    Body: CoursesCreateData["body"];
    Reply: CoursesCreateErrors & CoursesCreateResponses;
  }>;
  coursesLessonsIndex: RouteHandler<{
    Params: CoursesLessonsIndexData["path"];
    Querystring?: CoursesLessonsIndexData["query"];
    Reply: CoursesLessonsIndexResponses;
  }>;
  coursesLessonsCreate: RouteHandler<{
    Body: CoursesLessonsCreateData["body"];
    Params: CoursesLessonsCreateData["path"];
    Reply: CoursesLessonsCreateErrors & CoursesLessonsCreateResponses;
  }>;
  coursesLessonsShow: RouteHandler<{
    Params: CoursesLessonsShowData["path"];
    Reply: CoursesLessonsShowErrors & CoursesLessonsShowResponses;
  }>;
  coursesDestroy: RouteHandler<{
    Params: CoursesDestroyData["path"];
    Reply: CoursesDestroyErrors & CoursesDestroyResponses;
  }>;
  coursesShow: RouteHandler<{
    Params: CoursesShowData["path"];
    Reply: CoursesShowErrors & CoursesShowResponses;
  }>;
  coursesUpdate: RouteHandler<{
    Body: CoursesUpdateData["body"];
    Params: CoursesUpdateData["path"];
    Reply: CoursesUpdateErrors & CoursesUpdateResponses;
  }>;
  tokensCreate: RouteHandler<{
    Body: TokensCreateData["body"];
    Reply: TokensCreateErrors & TokensCreateResponses;
  }>;
  usersIndex: RouteHandler<{
    Querystring?: UsersIndexData["query"];
    Reply: UsersIndexResponses;
  }>;
  usersCreate: RouteHandler<{
    Body: UsersCreateData["body"];
    Reply: UsersCreateErrors & UsersCreateResponses;
  }>;
  usersDestroy: RouteHandler<{
    Params: UsersDestroyData["path"];
    Reply: UsersDestroyErrors & UsersDestroyResponses;
  }>;
  usersShow: RouteHandler<{
    Params: UsersShowData["path"];
    Reply: UsersShowErrors & UsersShowResponses;
  }>;
  usersUpdate: RouteHandler<{
    Body: UsersUpdateData["body"];
    Params: UsersUpdateData["path"];
    Reply: UsersUpdateErrors & UsersUpdateResponses;
  }>;
};
