// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type AuthInfo = {
  email: string;
  password: string;
};

export type Course = {
  id: number;
  name: string;
  description: string;
};

export type CourseCreateDto = {
  name: string;
  description: string;
};

export type CourseEditDto = {
  name?: string;
  description?: string;
};

export type CourseLesson = {
  id: number;
  courseId: number;
  name: string;
  body: string;
};

export type CourseLessonCreateDto = {
  name: string;
  body: string;
};

export type ForbiddenError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

export type NotFoundError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

/**
 * https://www.rfc-editor.org/rfc/rfc9457.html
 */
export type ProblemDetails = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

export type Timestamps = {
  [key: string]: unknown;
};

export type TokenInfo = {
  token: string;
};

export type UnauthorizedError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
};

export type UnprocessableEntityError = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  errors: Array<{
    message: string;
    rule: string;
    field: string;
  }>;
};

export type User = {
  id: number;
  fullName: string | null;
  email: string;
};

export type UserCreateDto = {
  fullName?: string;
  email: string;
};

export type UserEditDto = {
  fullName?: string;
};

export type Versions = "v1" | "v2";

export type CoursesIndexData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
  };
  url: "/courses";
};

export type CoursesIndexResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    data: Array<Course>;
  };
};

export type CoursesIndexResponse = CoursesIndexResponses[keyof CoursesIndexResponses];

export type CoursesCreateData = {
  body: CourseCreateDto;
  path?: never;
  query?: never;
  url: "/courses";
};

export type CoursesCreateErrors = {
  /**
   * Client error
   */
  422: UnprocessableEntityError;
};

export type CoursesCreateError = CoursesCreateErrors[keyof CoursesCreateErrors];

export type CoursesCreateResponses = {
  /**
   * The request has succeeded and a new resource has been created as a result.
   */
  201: Course;
};

export type CoursesCreateResponse = CoursesCreateResponses[keyof CoursesCreateResponses];

export type CoursesLessonsIndexData = {
  body?: never;
  path: {
    courseId: number;
  };
  query?: {
    page?: number;
  };
  url: "/courses/{courseId}/lessons";
};

export type CoursesLessonsIndexResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    data: Array<CourseLesson>;
  };
};

export type CoursesLessonsIndexResponse =
  CoursesLessonsIndexResponses[keyof CoursesLessonsIndexResponses];

export type CoursesLessonsCreateData = {
  body: CourseLessonCreateDto;
  path: {
    courseId: number;
  };
  query?: never;
  url: "/courses/{courseId}/lessons";
};

export type CoursesLessonsCreateErrors = {
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * Client error
   */
  422: UnprocessableEntityError;
};

export type CoursesLessonsCreateError =
  CoursesLessonsCreateErrors[keyof CoursesLessonsCreateErrors];

export type CoursesLessonsCreateResponses = {
  /**
   * The request has succeeded and a new resource has been created as a result.
   */
  201: CourseLesson;
};

export type CoursesLessonsCreateResponse =
  CoursesLessonsCreateResponses[keyof CoursesLessonsCreateResponses];

export type CoursesLessonsShowData = {
  body?: never;
  path: {
    courseId: number;
    id: number;
  };
  query?: never;
  url: "/courses/{courseId}/lessons/{id}";
};

export type CoursesLessonsShowErrors = {
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
};

export type CoursesLessonsShowError = CoursesLessonsShowErrors[keyof CoursesLessonsShowErrors];

export type CoursesLessonsShowResponses = {
  /**
   * The request has succeeded.
   */
  200: CourseLesson;
};

export type CoursesLessonsShowResponse =
  CoursesLessonsShowResponses[keyof CoursesLessonsShowResponses];

export type CoursesDestroyData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/courses/{id}";
};

export type CoursesDestroyErrors = {
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
};

export type CoursesDestroyError = CoursesDestroyErrors[keyof CoursesDestroyErrors];

export type CoursesDestroyResponses = {
  /**
   * There is no content to send for this request, but the headers may be useful.
   */
  204: void;
};

export type CoursesDestroyResponse = CoursesDestroyResponses[keyof CoursesDestroyResponses];

export type CoursesShowData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/courses/{id}";
};

export type CoursesShowErrors = {
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
};

export type CoursesShowError = CoursesShowErrors[keyof CoursesShowErrors];

export type CoursesShowResponses = {
  /**
   * The request has succeeded.
   */
  200: Course;
};

export type CoursesShowResponse = CoursesShowResponses[keyof CoursesShowResponses];

export type CoursesUpdateData = {
  body: CourseEditDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/courses/{id}";
};

export type CoursesUpdateErrors = {
  /**
   * Access is unauthorized.
   */
  401: UnauthorizedError;
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Client error
   */
  422: UnprocessableEntityError;
};

export type CoursesUpdateError = CoursesUpdateErrors[keyof CoursesUpdateErrors];

export type CoursesUpdateResponses = {
  /**
   * The request has succeeded.
   */
  200: Course;
};

export type CoursesUpdateResponse = CoursesUpdateResponses[keyof CoursesUpdateResponses];

export type TokensCreateData = {
  body: AuthInfo;
  path?: never;
  query?: never;
  url: "/tokens";
};

export type TokensCreateErrors = {
  /**
   * Client error
   */
  422: UnprocessableEntityError;
};

export type TokensCreateError = TokensCreateErrors[keyof TokensCreateErrors];

export type TokensCreateResponses = {
  /**
   * The request has succeeded and a new resource has been created as a result.
   */
  201: TokenInfo;
};

export type TokensCreateResponse = TokensCreateResponses[keyof TokensCreateResponses];

export type UsersIndexData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
  };
  url: "/users";
};

export type UsersIndexResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    data: Array<User>;
  };
};

export type UsersIndexResponse = UsersIndexResponses[keyof UsersIndexResponses];

export type UsersCreateData = {
  body: UserCreateDto;
  path?: never;
  query?: never;
  url: "/users";
};

export type UsersCreateErrors = {
  /**
   * Client error
   */
  422: UnprocessableEntityError;
};

export type UsersCreateError = UsersCreateErrors[keyof UsersCreateErrors];

export type UsersCreateResponses = {
  /**
   * The request has succeeded and a new resource has been created as a result.
   */
  201: User;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersDestroyErrors = {
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
};

export type UsersDestroyError = UsersDestroyErrors[keyof UsersDestroyErrors];

export type UsersDestroyResponses = {
  /**
   * There is no content to send for this request, but the headers may be useful.
   */
  204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersShowData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersShowErrors = {
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
};

export type UsersShowError = UsersShowErrors[keyof UsersShowErrors];

export type UsersShowResponses = {
  /**
   * The request has succeeded.
   */
  200: User;
};

export type UsersShowResponse = UsersShowResponses[keyof UsersShowResponses];

export type UsersUpdateData = {
  body: UserEditDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersUpdateErrors = {
  /**
   * The server cannot find the requested resource.
   */
  404: NotFoundError;
  /**
   * Client error
   */
  422: UnprocessableEntityError;
};

export type UsersUpdateError = UsersUpdateErrors[keyof UsersUpdateErrors];

export type UsersUpdateResponses = {
  /**
   * The request has succeeded.
   */
  200: User;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];
