// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zAuthInfo = z.object({
  email: z.string(),
  password: z.string(),
});

export const zBadRequestError = z.object({
  type: z.string().optional(),
  title: z.string().optional(),
  status: z.int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
});

export const zCourse = z.object({
  id: z.number(),
  name: z.string(),
  description: z.string(),
});

export const zCourseCreateDto = z.object({
  name: z.string(),
  description: z.string(),
});

export const zCourseEditDto = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
});

export const zCourseLesson = z.object({
  id: z.number(),
  courseId: z.number(),
  name: z.string(),
  body: z.string(),
});

export const zCourseLessonCreateDto = z.object({
  name: z.string(),
  body: z.string(),
});

export const zForbiddenError = z.object({
  type: z.string().optional(),
  title: z.string().optional(),
  status: z.int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
});

export const zNotFoundError = z.object({
  type: z.string().optional(),
  title: z.string().optional(),
  status: z.int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
});

/**
 * https://www.rfc-editor.org/rfc/rfc9457.html
 */
export const zProblemDetails = z.object({
  type: z.string().optional(),
  title: z.string().optional(),
  status: z.int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
});

export const zTimestamps = z.record(z.string(), z.unknown());

export const zTokenInfo = z.object({
  token: z.string(),
});

export const zTooManyRequestsError = z.object({
  type: z.string().optional(),
  title: z.string().optional(),
  status: z.int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
});

export const zUnauthorizedError = z.object({
  type: z.string().optional(),
  title: z.string().optional(),
  status: z.int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
});

export const zUnprocessableEntityError = z.object({
  type: z.string().optional(),
  title: z.string().optional(),
  status: z.int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
  errors: z.array(
    z.object({
      message: z.string(),
      rule: z.string(),
      field: z.string(),
    }),
  ),
});

export const zUser = z.object({
  id: z.number(),
  fullName: z.string().min(2).max(100).nullable(),
  email: z.string(),
});

export const zUserCreateDto = z.object({
  fullName: z.string().min(2).max(100).optional(),
  email: z.string(),
  password: z.string().min(8),
});

export const zUserEditDto = z.object({
  fullName: z.string().min(2).max(100).optional(),
  password: z.string().min(8).optional(),
});

export const zVersions = z.enum(["v1", "v2"]);

export const zCoursesIndexQuery = z.object({
  page: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional()
    .default(1),
});

/**
 * The request has succeeded.
 */
export const zCoursesIndexResponse = z.object({
  data: z.array(zCourse),
});

export const zCoursesCreateBody = zCourseCreateDto;

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zCoursesCreateResponse = zCourse;

export const zCoursesLessonsIndexPath = z.object({
  courseId: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

export const zCoursesLessonsIndexQuery = z.object({
  page: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional()
    .default(1),
});

/**
 * The request has succeeded.
 */
export const zCoursesLessonsIndexResponse = z.object({
  data: z.array(zCourseLesson),
});

export const zCoursesLessonsCreateBody = zCourseLessonCreateDto;

export const zCoursesLessonsCreatePath = z.object({
  courseId: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zCoursesLessonsCreateResponse = zCourseLesson;

export const zCoursesLessonsShowPath = z.object({
  courseId: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  id: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * The request has succeeded.
 */
export const zCoursesLessonsShowResponse = zCourseLesson;

export const zCoursesDestroyPath = z.object({
  id: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export const zCoursesDestroyResponse = z.void();

export const zCoursesShowPath = z.object({
  id: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * The request has succeeded.
 */
export const zCoursesShowResponse = zCourse;

export const zCoursesUpdateBody = zCourseEditDto;

export const zCoursesUpdatePath = z.object({
  id: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * The request has succeeded.
 */
export const zCoursesUpdateResponse = zCourse;

export const zTokensCreateBody = zAuthInfo;

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zTokensCreateResponse = zTokenInfo;

export const zUsersIndexQuery = z.object({
  page: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional()
    .default(1),
});

/**
 * The request has succeeded.
 */
export const zUsersIndexResponse = z.object({
  data: z.array(zUser),
});

export const zUsersCreateBody = zUserCreateDto;

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zUsersCreateResponse = zUser;

export const zUsersDestroyPath = z.object({
  id: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export const zUsersDestroyResponse = z.void();

export const zUsersShowPath = z.object({
  id: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * The request has succeeded.
 */
export const zUsersShowResponse = zUser;

export const zUsersUpdateBody = zUserEditDto;

export const zUsersUpdatePath = z.object({
  id: z
    .int()
    .gte(1)
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * The request has succeeded.
 */
export const zUsersUpdateResponse = zUser;
